#!/bin/sh
#
# Shell script that configures gnome-terminal to use solarized theme
# colors. Written for Ubuntu 11.10, untested on anything else.
#
# Solarized theme: http://ethanschoonover.com/solarized

PALETTE=
BG_COLOR=
FG_COLOR=

yel="#b58900"
ora="#cb4b16"
red="#dc322f"
mag="#d33682"
vio="#6c71c4"
blu="#268bd2"
cya="#2aa198"
gre="#859900"

b03="#002b36"
b02="#073642"
b01="#586e75"
b00="#657b83"
ba0="#839496"
ba1="#93a1a1"
ba2="#eee8d5"
ba3="#fdf6e3"

die () {
    2>&1 echo "$@"
    exit 1
}

dark () {
    PALETTE="${b02}:${red}:${gre}:${yel}:${blu}:${mag}:${cya}:${ba2}:${b03}:${ora}:${b01}:${b00}:${ba0}:${vio}:${ba1}:${ba3}"
    BG_COLOR="${b03}"
    FG_COLOR="${ba0}"
}

light () {
    PALETTE="${ba2}:${red}:${gre}:${yel}:${blu}:${mag}:${cya}:${b02}:${ba3}:${ora}:${ba1}:${ba0}:${b00}:${vio}:${b01}:${b03}"
    BG_COLOR="${ba3}"
    FG_COLOR="${b00}"
}

make_changes () {
    gconftool-2 --set "/apps/gnome-terminal/profiles/Default/use_theme_background" --type bool false
    gconftool-2 --set "/apps/gnome-terminal/profiles/Default/use_theme_colors" --type bool false
    gconftool-2 --set "/apps/gnome-terminal/profiles/Default/palette" --type string "$PALETTE"
    gconftool-2 --set "/apps/gnome-terminal/profiles/Default/background_color" --type string "$BG_COLOR"
    gconftool-2 --set "/apps/gnome-terminal/profiles/Default/foreground_color" --type string "$FG_COLOR"
}

reverse_solarized() {
    # dark and light set globals, which we then test.

    found=false
    cur_palette=$(gconftool-2 --get "/apps/gnome-terminal/profiles/Default/palette")

    dark
    if [ "$PALETTE" = "$cur_palette" ]; then
        found=true
    fi

    light
    if ! $found ; then
        if [ "$PALETTE" = "$cur_palette" ]; then
            found=true
            dark
        fi
    fi
    $found
    return $?
}

main () {
    case "$1" in
        "dark" | "light")
            $1 ;;
        *)
            reverse_solarized ||
                die "Usage: solarize [light | dark]"
            ;;
    esac
    make_changes
}

main "$@"
